// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"custom-echo-ctx/internal"
)

// Injectors from wire.go:

func Ready() *internal.Server {
	server := internal.NewServer()
	return server
}

func MockReady() *internal.Server {
	server := internal.NewServer()
	return server
}
