version: "3"

services:
  swagger-ui:
    image: pentusha/swagger-ui-crossbuild
    container_name: "swagger-ui"
    ports:
      - "8001:8080"
    volumes:
      - ./openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
